version: "2.2"
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/opt/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    stdin_open: true
    tty: true
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eos_snapshot
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3306"
  redis:
    build: ./docker/redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
